#!/bin/sh

# $Id$

#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap
#
#xmodmap "/home/just22/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &
# gkrellm -w &
conky -c ~/.config/conky/conkyrc-statusline &

sleep 5
bbpager &

#conky -c ~/.config/conky/conkyrc-rwin &
/usr/local/libexec/tray-app/eject -i &
/usr/local/libexec/tray-app/sound -i &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.
#
exec fluxbox
# or, if you want to keep a log:
# exec fluxbox -log "/home/just22/.fluxbox/log"
