#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  fluxbox(1) startup-script
# ----------------------------------------------------------------------

# Screen locker
xautolock -time 10 -locker slock &

# Start a session bus instance of dbus-daemon
if [ -x /usr/local/bin/dbus-launch -a -z "${DBUS_SESSION_BUS_ADDRESS}" ]; then
        eval `dbus-launch --sh-syntax --exit-with-x11`
fi

# dunst notification system
mkdir -p "${XDG_DATA_HOME:-$HOME/.local/share}/dbus-1/services"
ln -sf \
    "/usr/local/share/dbus-1/services/org.knopwob.dunst.service" \
    "${XDG_DATA_HOME:-$HOME/.local/share}/dbus-1/services/org.freedesktop.Notifications.service"

# Process monitor
xterm -title "Process monitor" -e top &

# System statistics
xterm -title "System stats" -e systat &

# System log
sleep 1
xkill -id $(xwininfo -name xconsole |
            egrep -o "Window id: 0x[0-9a-fA-F]+" |
            cut -d: -f2)
xterm -title "System log" -e "tail -f /var/log/messages" &

# Compositor manager
xcompmgr &

# Set wallpaper
nitrogen --restore || fbsetbg -l

# Statusbar
pkill -x space_dapp; (sleep 1; space_dapp $((($(screen-width) - 1))) 17) &

(sleep 3; dbar |
    dzen2 -title-name dbar \
          -bg "#eee8d5" -fg "#073642" -fn "DejaVu Sans Mono:size=9" \
          -p -e "" -geometry +0+1 -expand left -dock -xs "${xs:-1}") &

# This is a bad hack!!! Fluxbox doesn't manage dock apps properly
# Note: xprop is unable to set multiple fields for a property...
(sleep 4;
 xprop -name dbar -f _NET_WM_STATE 32a \
       -set _NET_WM_STATE '_NET_WM_STATE_SKIP_PAGER') &

pkill -x bbpager; (sleep 6; bbpager) &

# Tray apps
sleep 1; /usr/local/libexec/tray-app/sound -i &
sleep 2; cal-tray &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.
#
#exec fluxbox

# Or, if you want to keep a log:
mv -f ~/.fluxbox/fluxbox.log{,.old} 2> /dev/null
exec fluxbox -log ~/.fluxbox/fluxbox.log
