#!/bin/sh

# ----------------------------------------------------------------------
#  $Id$
#
#  fluxbox(1) startup-script
# ----------------------------------------------------------------------

# Change your keymap
#
#xmodmap "/home/just22/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &
# gkrellm -w &

# Compositor manager
xcompmgr &

# Set the root window background
fbsetroot -gradient Vertical -from rgb:07/36/42 -to rgb:58/6E/75

# Xscreensaver
xscreensaver &

# Battery status check daemon
~/bin/check-batt-status &

# Desktop management
(sleep 1; dbus-launch pcmanfm --desktop) &

# Statusbar
(sleep 4; statusbar) &

# Reserve space for statusbar
# (Just a WA, since dzen2 doesn't play well with Fluxbox's slit)
(sleep 4; space_dapp) &

# Tray apps
#/usr/local/libexec/tray-app/sound -i &
hp-systray &


# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.
#
#exec fluxbox

# Or, if you want to keep a log:
mv -f ~/.fluxbox/fluxbox.log{,.old} 2> /dev/null
exec fluxbox -log ~/.fluxbox/fluxbox.log
