# Status line
set-option -g status-position bottom
set-option -g status-left-length  100
set-option -g status-right-length  80

# basic, rounded, slanted, custom, or none
set-option -g @catppuccin_window_status_style "basic"

set-option -g @catppuccin_window_current_text " #W"
set-option -g @catppuccin_window_text " #W"

set-option -g @catppuccin_session_icon " S "
set-option -g @catppuccin_status_left_separator " "
set-option -g @catppuccin_session_text " #S "
set-option -g @catppuccin_status_connect_separator "no"

set-option -g status-left "#{E:@catppuccin_status_session}"
set-option -g status-right 'Pane #I.#P: #T'

